version: '3'
services:
  products-service:
    build:
      context: ./products-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  payments-service:
    build:
      context: ./payments-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  shipping-service:
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"

  orders-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_ARGS: "http://payments-service:8080 http://shipping-service:8080 http://products-service:8080"
